import { asset, cn } from '@/lib/utils';
import manifest from '@/lib/image-manifest.json';

type ManifestEntry = { blur: string; widths: number[]; ratio: number };

const images = manifest as Record<string, ManifestEntry>;

type PictureProps = {
  /** File name without extension, e.g. "hero-main". */
  name: string;
  /** Alternative text. An empty string marks a purely decorative image. */
  alt: string;
  /**
   * Frame aspect ratio. Defaults to the ratio the image was cropped to; pass a
   * value to fit the image into a different shape (object-cover handles the
   * remainder).
   */
  ratio?: number;
  /** Size hint for the browser - the key to picking the right srcset entry. */
  sizes?: string;
  className?: string;
  imgClassName?: string;
  /** Above-the-fold hero loads eagerly, everything else lazily. */
  priority?: boolean;
};

/**
 * Image served as AVIF + WebP with an LQIP placeholder.
 *
 * Under output:'export' next/image has no optimizing server, so we rely on
 * pre-built variants and a native <picture>. The width list comes from the
 * manifest generated by scripts/optimize-images.mjs, which guarantees the
 * srcset never points at a file that does not exist.
 */
export function Picture({
  name,
  alt,
  ratio,
  sizes = '100vw',
  className,
  imgClassName,
  priority = false,
}: PictureProps) {
  const entry = images[name];

  // A missing entry means a typo in the name or an unrun optimization script.
  // Showing an empty frame beats breaking the page layout.
  if (!entry) {
    return (
      <div
        className={cn('block bg-bg-muted', className)}
        style={{ aspectRatio: ratio ?? 1 }}
        aria-hidden={alt === '' ? true : undefined}
        role={alt === '' ? undefined : 'img'}
        aria-label={alt || undefined}
      />
    );
  }

  const displayRatio = ratio ?? entry.ratio;
  const largest = entry.widths[entry.widths.length - 1]!;

  const srcSet = (extension: string) =>
    entry.widths
      .map((width) => `${asset(`/images/${name}-${width}.${extension}`)} ${width}w`)
      .join(', ');

  return (
    <picture
      className={cn('block overflow-hidden', className)}
      style={{ aspectRatio: displayRatio }}
    >
      <source type="image/avif" srcSet={srcSet('avif')} sizes={sizes} />
      <source type="image/webp" srcSet={srcSet('webp')} sizes={sizes} />
      <img
        src={asset(`/images/${name}-${largest}.webp`)}
        alt={alt}
        // Intrinsic dimensions reserve space before the image loads (CLS).
        width={largest}
        height={Math.round(largest / entry.ratio)}
        loading={priority ? 'eager' : 'lazy'}
        decoding={priority ? 'sync' : 'async'}
        fetchPriority={priority ? 'high' : 'auto'}
        className={cn('h-full w-full object-cover', imgClassName)}
        style={{
          backgroundImage: `url("${entry.blur}")`,
          backgroundSize: 'cover',
          backgroundPosition: 'center',
        }}
      />
    </picture>
  );
}
